<a href="https://colab.research.google.com/github/mateuszklimczyk97/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)
>
>Instalacji biblioteki NumPy:


```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe elementy na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)


## Podstawy

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np)) #klasy biblioteki np

In [ ]:
help(np.array) #pomoc do funkcji array

### 1D Array

In [ ]:
x = np.array([1, 5])
x

array([1, 5])

In [ ]:
print(x)

[1 5]


In [ ]:
type(x)

numpy.ndarray

### Atrybuty klasy np.array:

In [ ]:
x.ndim #wymiar tablicy

1

In [ ]:
x.shape #kształt tablicy

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype #typ danych

dtype('int64')

In [ ]:
x = np.array([1.3, 1.2, 2.4])
print(x)

[1.3 1.2 2.4]


In [ ]:
x.dtype

dtype('float64')

### 2D Array

In [ ]:
x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x = np.array([[1,2,3],[4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

### 3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,3],
     [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

## Typy danych

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.1, 2.0, 3.5])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='complex') #typ liczb złożonych
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.1, 2.0, 3.5], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype = np.int8) #liczby całkowite 8-bitowe
A.dtype

dtype('int8')

## Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10)) #tablica samych '0'

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5), dtype='int') #tablica samych '1'

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int') #tablica wartości podanych

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5)) #zmiana wygladu tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1)) #dobieranie liczby kolumn automatycznie przez python

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Podstawowe operacje na tablicach

In [ ]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
np.add(A,B) #dodawanie tablic przez np

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B) #odejmowanie tablic

array([0, 2, 1, 0])

In [ ]:
np.multiply(A,B) #mnozenie tablic

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A,B) #dzielenie tablic

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3 #dodanie pewnej stałej do tablicy 'A'

array([6, 4, 7, 5])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

### Mnożenie macierzowe

In [ ]:
X = np.array([[1,3], [-2,0]]) 
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

## Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn() #losowa wartosc z rozkladu normalnego

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand() #rozklad jednostajny

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.randint(10) #liczby całkowite mniejsze niz '10' losowo

2

In [ ]:
np.random.randint(low=10, high=101, size = 10)

array([68, 33, 69, 12, 72, 45, 77, 92, 56, 30])

In [ ]:
np.random.choice([4, 2, 1, 3]) #losowy element z listy

1

In [ ]:
np.random.choice(['python','java','sql'])

'java'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([7, 9, 0, 6, 4, 3, 2, 5, 8, 1])

## Podstawowe funkcje

In [ ]:
np.exp(2) 

7.38905609893065

In [ ]:
np.sqrt(4) #pierwiastek kwadratowy

2.0

In [ ]:
np.all([2,3,1]) #czy kazdy obiekt w liscie jest Prawdą

True

In [ ]:
np.any([1,2,1]) #sprawdza czy jakikolwiek obiekt jest Prawdą

True

In [ ]:
bool(1.3)

True

In [ ]:
A = np.random.rand(5)
A

array([0.8811032 , 0.58127287, 0.88173536, 0.69253159, 0.72525428])

In [ ]:
np.argmax(A) #zwraca index ktory jest najwieksza wartoscia w danej tablicy/listy

2

In [ ]:
A[np.argmax(A)]

0.8817353618548528

In [ ]:
np.argmin(A)

1

In [ ]:
np.argsort(A) #sortowanie tablicy indexami rosnaco

array([1, 3, 4, 0, 2])

In [ ]:
np.max(A) #najwieksza wartosc z tablicy

0.8817353618548528

In [ ]:
np.mean(A) #srednia

0.7523794602998559

In [ ]:
np.median(A) #mediana

0.7252542798196405

In [ ]:
np.std(A) #odchylenie standardowe

0.11567001081870261

## Indeksowanie, wycinanie

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
 # A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0,2,5,7]]

array([0, 2, 5, 7])

In [ ]:
A[-1]

19

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [5]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0] #wyciecie pierwszego wiersza

array([0, 1, 2, 3, 4])

In [ ]:
A[:, 1] #wyciecie kolumny drugiej

array([ 1,  6, 11, 16])

In [ ]:
A[1,3] #wyciecie konkretnego elementu

8

In [ ]:
A[1:3, 1:4] #wyciecie konkretnego fragmentu

array([[ 6,  7,  8],
       [11, 12, 13]])

In [6]:
A[1,2] = 14 #zmiana danego elementu w tablicy
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Iteracja po tablicach

In [7]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [10]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [11]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


## Zmiana rozmiaru tablic

In [12]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
A.shape

(4, 5)

In [15]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
A.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
A.T #transponowanie tablicy

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## Maski logiczne

In [20]:
A = np.arange(start = -10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [21]:
A > 0 #gdzie w tablicy wartosci sa wieksze od zera {bool}

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [24]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [26]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])