<a href="https://colab.research.google.com/github/mateuszklimczyk97/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Funkcje statystyczne

In [1]:
import numpy as np

In [2]:
price = np.array([[12.40,12.80,11.90,12.60,1000],
                  [12.50,13.00,11.70,12.20,2000],
                  [12.20,13.40,12.20,13.20,1500]
                  ])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


### sum()

In [5]:
price.sum()

4650.1

In [6]:
price.sum(axis=0) #suma kolumn

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [7]:
price.sum(axis=1) #suma wierszy

array([1049.7, 2049.4, 1551. ])

In [8]:
np.sum(price)

4650.1

### min()

In [10]:
np.min(price)

11.7

In [11]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

### max()

In [13]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

### median()

In [14]:
np.median(price)

12.6

### mean()

In [24]:
np.set_printoptions(precision=2, suppress=True)
np.mean(price, axis=0)

array([  12.37,   13.07,   11.93,   12.67, 1500.  ])

### std()

In [22]:
np.std(price, axis=0)

array([  0.12,   0.25,   0.21,   0.41, 408.25])

### var()

In [23]:
np.var(price,axis=0)

array([     0.02,      0.06,      0.04,      0.17, 166666.67])