<a href="https://colab.research.google.com/github/mateuszklimczyk97/data-science-bootcamp/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)
>
>Instalacji biblioteki NumPy:


```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)



## Podstawy

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np)) #klasy biblioteki np

In [ ]:
help(np.array) #pomoc do funkcji array

### 1D Array

In [ ]:
x = np.array([1, 5])
x

array([1, 5])

In [ ]:
print(x)

[1 5]


In [ ]:
type(x)

numpy.ndarray

### Atrybuty klasy np.array:

In [ ]:
x.ndim #wymiar tablicy

1

In [ ]:
x.shape #kształt tablicy

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype #typ danych

dtype('int64')

In [ ]:
x = np.array([1.3, 1.2, 2.4])
print(x)

[1.3 1.2 2.4]


In [ ]:
x.dtype

dtype('float64')

### 2D Array

In [ ]:
x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x = np.array([[1,2,3],[4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

### 3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,3],
     [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

## Typy danych

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.1, 2.0, 3.5])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='complex') #typ liczb złożonych
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.1, 2.0, 3.5], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype = np.int8) #liczby całkowite 8-bitowe
A.dtype

dtype('int8')

## Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10)) #tablica samych '0'

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5), dtype='int') #tablica samych '1'

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int') #tablica wartości podanych

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5)) #zmiana wygladu tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1)) #dobieranie liczby kolumn automatycznie przez python

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Podstawowe operacje na tablicach

In [3]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [4]:
A + B

array([6, 0, 7, 4])

In [5]:
A * B

array([ 9, -1, 12,  4])

In [8]:
np.add(A,B) #dodawanie tablic przez np

array([6, 0, 7, 4])

In [9]:
np.subtract(A,B) #odejmowanie tablic

array([0, 2, 1, 0])

In [10]:
np.multiply(A,B) #mnozenie tablic

array([ 9, -1, 12,  4])

In [11]:
np.divide(A,B) #dzielenie tablic

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [6]:
A + 3 #dodanie pewnej stałej do tablicy 'A'

array([6, 4, 7, 5])

In [7]:
A + 3*B

array([12, -2, 13,  8])

### Mnozenie macierzowe

In [14]:
X = np.array([[1,3], [-2,0]]) 
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [15]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [16]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [17]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [18]:
X @ Y

array([[  3,   6],
       [-12,   0]])