<a href="https://colab.research.google.com/github/mateuszklimczyk97/data-science-bootcamp/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)
>
>Instalacji biblioteki NumPy:


```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. 



### Podstawy

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np)) #klasy biblioteki np

In [ ]:
help(np.array) #pomoc do funkcji array

#### 1D Array

In [ ]:
x = np.array([1, 5])
x

array([1, 5])

In [ ]:
print(x)

[1 5]


In [ ]:
type(x)

numpy.ndarray

#### Atrybuty klasy np.array:

In [ ]:
x.ndim #wymiar tablicy

1

In [ ]:
x.shape #kształt tablicy

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype #typ danych

dtype('int64')

In [ ]:
x = np.array([1.3, 1.2, 2.4])
print(x)

[1.3 1.2 2.4]


In [ ]:
x.dtype

dtype('float64')

### 2D Array

In [ ]:
x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x = np.array([[1,2,3],[4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

### 3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,3],
     [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

## Typy danych

In [3]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [4]:
A = np.array([1.1, 2.0, 3.5])
A.dtype

dtype('float64')

In [5]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [7]:
A = np.array([1, 2, 3], dtype='complex') #typ liczb złożonych
A.dtype

dtype('complex128')

In [8]:
A = np.array([1.1, 2.0, 3.5], dtype='int')
A.dtype

dtype('int64')

In [9]:
A

array([1, 2, 3])

In [10]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [11]:
A = np.array([24, 120, 230], dtype = np.int8) #liczby całkowite 8-bitowe
A.dtype

dtype('int8')